# Use root/example as user/password credentials
version: '3.1'

services:
  ieaw_mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ieaw2023! 
    volumes: 
      - ieaw_mongodb_volume:/data/db
  ieaw_mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ieaw2023!
      ME_CONFIG_MONGODB_URL: mongodb://root:ieaw2023!@ieaw_mongo:27017/
volumes:
  ieaw_mongodb_volume:
